# Generated by Django 5.1.2 on 2024-10-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_player_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='league_type',
            new_name='league',
        ),
        migrations.AddField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(related_name='seasons', through='league.SeasonTeam', to='league.team'),
        ),
    ]
