# Generated by Django 5.1.2 on 2024-10-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_rename_league_type_season_league_season_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchday',
            options={'ordering': ['season', 'round_number']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-year']},
        ),
        migrations.AlterUniqueTogether(
            name='matchday',
            unique_together={('season', 'round_number')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('year', 'league')},
        ),
    ]
