# Generated by Django 5.1.2 on 2024-10-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_venue_team_venue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_day']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Finished', 'Finished')], default='Not Started', max_length=20),
        ),
        migrations.AlterField(
            model_name='seasonteam',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='teams', to='league.player'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('match_day', 'home_team', 'away_team')},
        ),
    ]
