# Generated by Django 5.1.2 on 2024-10-23 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_alter_match_options_alter_team_options_match_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='matchday',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 23)),
            preserve_default=False,
        ),
    ]
