# Generated by Django 5.1.2 on 2024-10-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_rename_match_date_match_date_matchday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentscore',
            name='away_players',
            field=models.ManyToManyField(blank=True, related_name='away_segments', to='league.player'),
        ),
        migrations.AddField(
            model_name='segmentscore',
            name='home_players',
            field=models.ManyToManyField(blank=True, related_name='home_segments', to='league.player'),
        ),
        migrations.AddField(
            model_name='segmentscore',
            name='segment_type',
            field=models.CharField(choices=[('D1', 'Doubles 1'), ('D2', 'Doubles 2'), ('S1', 'Singles 1'), ('D3', 'Doubles 3'), ('S2', 'Singles 2'), ('D4', 'Doubles 4'), ('D5', 'Doubles 5')], default='D1', max_length=2),
            preserve_default=False,
        ),
    ]
