# Generated by Django 5.1.2 on 2024-10-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_segmentscore_away_players_segmentscore_home_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentscore',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='segmentscore',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
