# Generated by Django 5.1.2 on 2024-10-23 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_alter_segmentscore_away_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_day'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='matchday',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
    ]
