# Generated by Django 5.1.2 on 2024-10-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_alter_match_options_alter_matchday_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeagueTable',
        ),
    ]
